### ISSUE TITLE
does alexa support exclamation mark?

### ISSUE THREAD

**Issue by jwpnet** [alexa/skill-sample-nodejs-fact#1]
The documentation on amazon developer site only mentions "." "," "?" as characters that influence the speech. Does exclamation mark actually change alexa's voice? I can't hear a difference.

**Comment by deegles** [comment]
Hi Jonathan,

Currently there are is a limited set of characters that influence the Alexa's Text-to-speech (TTS) rendering. You can use SSML to set the pronunciation of a word or to add pauses as needed.

SSML Reference: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference

Also, take a look at our Voice Design Best Practices page for some additional tips.

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-voice-design-best-practices
