### ISSUE TITLE
How to maintain the session?

### ISSUE THREAD

**Issue by alexa-ai** [alexa/skill-sample-nodejs-fact#10]
Hi, I am modifying the code to include repeat intent. I need to maintain the session attributes to get the repeat working. If you know how to maintain the session, please let me know. Thanks.

FYI -- The following is the code I added for repeatIntent: 

`    'AMAZON.RepeatIntent': function () {
        var reprompt = this.t("HELP_MESSAGE");        
        console.log('Inside RepeatIntent Stored speech attributes: ' + this.attributes['speech']);        
        this.emit(':ask', this.attributes['speech'], reprompt);
    },`

**Comment by furkando** [comment]
```
var speechOutput = "Here's your fact: " + randomFact  + "Do you want more facts?" ;
var reprompt = "Do you want more `facts?";`
this.emit(':askWithCard', speechOutput,reprompt, SKILL_NAME, randomFact)
```;
you can write like this to maintain the session

**Comment by alexa-ai** [comment]
Thanks @furkandoganktf. I am not sure if this will provide correct fact when the user says repeat -- which was the goal. I had to use alexa-sdk to accomplish that.
