### ISSUE TITLE
Sample code in tutorial and Lambda code from template are not same

### ISSUE THREAD

**Issue by hpj1992** [alexa/skill-sample-nodejs-fact#104]
Hi,

1) https://github.com/alexa/skill-sample-nodejs-fact/blob/master/instructions/2-lambda-function.md
2) Step 13
3) Linked here: https://github.com/alexa/skill-sample-nodejs-fact/blob/master/lambda/custom/index.js
4) Code in #4 should be available in Templates in Lambda. But that is not the case. 
5) Code from lambda template is completely different.
6) Not easy to understand for the ASK customer/developer

**Comment by chfw** [comment]
I found the same. 

First, I found the latest youtube video https://www.youtube.com/watch?v=QkbXjknPoXc after following a few out-dated medium tutorials.

But still, the youtube video is also out-dated . I have to copy and paste the lambda custom index.js to amazon lambda console to get it to work.

**Comment by theNaut1lus** [comment]
Is anyone still working on the or could I have a go? @franklin-lobb

**Comment by niceguydave** [comment]
> Is anyone still working on the or could I have a go? @franklin-lobb

I'm sure @franklin-lobb would be happy for you to put out a PR 👍

**Comment by dash-mode** [comment]
Not exactly the same issue, but when I fork this repository into my github account, I get a different index.js. Please look into it.

**Comment by aszk** [comment]
We removed AWS Lambda function instruction. Please use the code form repository.
