### ISSUE TITLE
I would like to modify the skill to have  facts for an specific planet.

### ISSUE THREAD

**Issue by tommycr** [alexa/skill-sample-nodejs-fact#109]
In order to acquire more "skills" on development of Alexa Skills I would like to modify this  code and go in a different path.    I would like to: 
1.) call the skill  "Alexa, open space curiosities.. "
2.) Alexa responds "For Which planet are you looking for facts  ?"
3.) I will respond for example "Saturn"
4.) Then alexa goes to the fact "website database" and respond with a fact BUT just for the chosed planet.

Somebody has ideas on how to start ?   
I guess first I need to work with the slots and then with the index.js file   don´t ?

**Comment by franklin-lobb** [comment]
@tommycr check out this sample: https://github.com/alexa/skill-sample-nodejs-fact-in-skill-purchases

Look beyond the In-Skill Purchasing and you'll see it's a fact-by-category skill.  Make the planets your categories, and then update the source of the data (or embed the data).

You may want to explore the In-Skill Purchasing while you're at it.  :)

**Comment by tommycr** [comment]
@franklin-lobb . Thank you very much, for your great Help !  I think is perfect for me, because force me to understand the lambda environment, (index.js) but still complicated for me.....
First I am "cleaning" the code by removing all the unnecessary sentences, BUT I have no luck, trying to pass it through the dialog model.  I just want  to read the "facts" from the embedded data, not from data sources yet...  By the way,  I am also translating  the skill to Spanish language as well  ( es-ES) this task is working well so far.  The "In-Skill Purchasing" will be the next step, for now,  I want to feel good,  with the basics...

**Comment by franklin-lobb** [comment]
In-Skill Purchasing is only available in en-US, so if you're aiming for es-ES, no need to work on ISP's (yet).

If you need additional assistance, open a new issue or check out the [forums](https://forums.developer.amazon.com/spaces/165/index.html)

Good luck!
