### ISSUE TITLE
Proposal: add external API usage with async/await to example

### ISSUE THREAD

**Issue by bluepuma77** [alexa/skill-sample-nodejs-fact#129]
What I am missing so far from the basic skill examples in NodeJS is the use of an API.

alexa / skill-sample-nodejs-hello-world
alexa / skill-sample-nodejs-fact
alexa / skill-sample-nodejs-first-skill
alexa / skill-sample-nodejs-trivia
alexa / skill-sample-nodejs-quiz-game

How do you call an external service and process the response, especially with async/await.
 
Or did I just didn't see it when looking through the source?

**Comment by aszk** [comment]
Thank you for asking. However this skill sample doesn't focus on calling external API.
Please refer our blog posts for more information.

- https://developer.amazon.com/blogs/alexa/post/4a46da08-d1b8-4d8e-9277-055307a9bf4a/alexa-skill-recipe-update-call-and-get-data-from-external-apis
- https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2019/05/alexa-skill-recipe-update-making-http-requests-to-get-data-from-an-external-api-using-the-ask-software-development-kit-for-node-js-version-2
