### ISSUE TITLE
Having issues "errorMessage": "Cannot find module '/var/task/index'",

### ISSUE THREAD

**Issue by nmwalkers** [alexa/skill-sample-nodejs-fact#13]
I am on mac and for some reason this happens when i try on Lambda to test the function 

{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": [
    "require (internal/module.js:12:17)"
  ]
}

**Comment by shootoke** [comment]
I have the same issue here. Could anybody help, please?

**Comment by cancinos** [comment]
This link should help you guys [Zipping files for AWS](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/applications-sourcebundle.html#using-features.deployment.source.gui) @shootoke @nmwalkers

**Comment by thucldnguyen** [comment]
I figured that I just needed to put the `index.js` file in the same folder as `node_modules` before zipping and the problem went away.
