### ISSUE TITLE
what is .t() in this line of code randomFact = requestAttributes.t('FACTS');?

### ISSUE THREAD

**Issue by AyushiMidha** [alexa/skill-sample-nodejs-fact#130]
I didn't get what is .t( ) in this line const randomFact = requestAttributes.t('FACTS');.
Is t( ) is an inbuilt function?
what is it doing?

**Comment by mauriliofilho** [comment]
This is part of Interceptors method, to load strings const based on your language/locale of you Skill is

look at     line 148 on attributes.t = function translate(...args) {
this is where .t() is loaded with your strings 'FACTS' on bottom of file, you  find all string to your skill based on language/locale
