### ISSUE TITLE
Broken links in the docs

### ISSUE THREAD

**Issue by zoomerkind** [alexa/skill-sample-nodejs-fact#132]
"If this is your first skill, choose the Alexa-Hosted backend instructions to get started quickly.
If you want to manage the backend resources in your own AWS account, you can follow the AWS-Hosted instructions.
Developers with the ASK Command Line Interface configured may follow the ASK CLI instructions."

Ask CLI and AWS-Hosted instruction links are broken.

**Comment by mauriliofilho** [comment]
Follow folder "instructions" on root of the folder code, thats is all files with tutoral sequence of learning!

**Comment by aszk** [comment]
Updated link.
