### ISSUE TITLE
doesn't create a skill

### ISSUE THREAD

**Issue by holla2040** [alexa/skill-sample-nodejs-fact#147]
I've tried several times, something happens then rollback occurs. Once rollback completes, no skill shows up and I can't use the template to create a skill with the same name.

**Comment by sjdee** [comment]
Hi mate, were you successful in getting this setup? trying to work this out myself

**Comment by MarioPelletier** [comment]
Same problem.  Is it possible that the nodejs10.x is the problem? 

Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs14.x) while creating or updating functions.

**Comment by aszk** [comment]
We have updated the serverless app. You should be able to deploy it.
