### ISSUE TITLE
de-DE Model incorrect

### ISSUE THREAD

**Issue by CommanderRedYT** [alexa/skill-sample-nodejs-fact#148]
The de-DE model is definitely not german, but danish. Please revert changes of commit c1cb2284e3b76fc83f5a05e534062b1eee4f111f to the file

**Comment by kweekhant** [comment]
Termux

**Comment by Sakib6** [comment]
[
  {"id":1, "name":"Kevin Bacon", "birthday":"1958-07-08"},
  {"id":2, "name":"Antonio Banderas", "birthday":"1960-08-10"},
  {"id":3, "name":"Pierce Brosnan", "birthday":"1953-05-16"},
  {"id":4, "name":"Sandra Bullock", "birthday":"1964-07-26"},
  {"id":5, "name":"Steve Buscemi", "birthday":"1957-12-13"},
  {"id":6, "name":"Nicolas Cage", "birthday":"1964-01-07"},
  {"id":7, "name":"Jim Carrey", "birthday":"1962-01-17"},
  {"id":8, "name":"George Clooney", "birthday":"1961-05-06"},
  {"id":9, "name":"Sean Connery", "birthday":"1930-08-25"},
  {"id":10, "name":"Leonardo DiCaprio", "birthday":"1974-11-11"},
  {"id":11, "name":"Samuel L. Jackson", "birthday":"1948-12-21"},
  {"id":12, "name":"Jennifer Lopez", "birthday":"1969-07-24"},
  {"id":13, "name":"Keanu Reeves", "birthday":"1964-09-02"},
  {"id":14, "name":"Robert Downey Jr.", "birthday":"1965-04-04"},
  {"id":15, "name":"Spike Lee", "birthday":"1957-03-20"},
  {"id":16, "name":"Aishwarya Rai", "birthday":"1973-11-01"},
  {"id":17, "name":"Awkwafina", "birthday": "1988-06-02"},
  {"id":18, "name":"Priyanka Chopra", "birthday":"1982-07-18"},
  {"id":19, "name":"Randall Park", "birthday":"1974-03-23"},
  {"id":20, "name":"John Boyega", "birthday":"1992-03-17"}
]

**Comment by gilleswb** [comment]
Reviewing de-DE model and confirmed index.js & de-DE.json model has danish samples instead of german.

Considering updating accordingly or reverting changes back to commit c1cb2284e3b76fc83f5a05e534062b1eee4f111f

**Comment by gilleswb** [comment]
closing this issue as we are preparing to send a PR to update de-DE model for German locale in order this address this report. This should be addressed following PR review and merge request. 

Thanks @CommanderRedYT for reporting this
