### ISSUE TITLE
missing instructions for first lambda role

### ISSUE THREAD

**Issue by danainschool** [alexa/skill-sample-nodejs-fact#15]
the instructions referenced in 2-lambda-function.md for setting up your first lambda role https://github.com/alexa/skill-sample-nodejs-fact/blob/master/step-by-step/LAMBDAROLE.md is missing.

**Comment by pavanpo** [comment]
We will get it fixed. For now, pls. refer to https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/deploying-a-sample-skill-to-aws-lambda#creating-the-lambda-function-for-the-sample (relevant section copied below):

Defining a New Role for the Function

The role specifies the AWS resources your function can access. To create a new role while configuring your function:

    For Role (under Lambda function handler and role), select Create new role from template(s).
    Enter the Role Name: lambda_basic_execution
    From the Policy templates list, select Simple Microservice permissions.

**Comment by jeffblankenburg** [comment]
This has been fixed.  My apologies for not updating this.
