### ISSUE TITLE
The remote endpoint could not be called, or the response it returned was invalid.

### ISSUE THREAD

**Issue by swapnilsaykar** [alexa/skill-sample-nodejs-fact#27]
I am new at developing with alexa. I followed to tutorial but when I get into the testing section it gives me an error:
The remote endpoint could not be called, or the response it returned was invalid.

Don't know what I did wrong - the arn is copied correctly.
I'm following the tutorial here: https://developer.amazon.com/alexa-skills-kit/tutorials/fact-skill-4

I am facing the issue in both N Virginia and Ireland regions

**Comment by swapnilsaykar** [comment]
In Cloudwatch logs, this is the error I am getting:

{
    "errorMessage": "No 'Unhandled' function defined for event: Unhandled",
    "errorType": "Error",
    "stackTrace": [
        "AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:194:15)",
        "AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:160:23)",
        "HandleLambdaEvent.i18n.use.init (/var/task/node_modules/alexa-sdk/lib/alexa.js:113:29)",
        "/var/task/node_modules/alexa-sdk/node_modules/i18next/dist/commonjs/i18next.js:190:9",
        "done (/var/task/node_modules/alexa-sdk/node_modules/i18next/dist/commonjs/i18next.js:281:21)",
        "/var/task/node_modules/alexa-sdk/node_modules/i18next/dist/commonjs/i18next.js:302:7",
        "I18n.loadResources (/var/task/node_modules/alexa-sdk/node_modules/i18next/dist/commonjs/i18next.js:238:7)",
        "I18n.changeLanguage (/var/task/node_modules/alexa-sdk/node_modules/i18next/dist/commonjs/i18next.js:301:10)",
        "load (/var/task/node_modules/alexa-sdk/node_modules/i18next/dist/commonjs/i18next.js:186:14)",
        "I18n.init (/var/task/node_modules/alexa-sdk/node_modules/i18next/dist/commonjs/i18next.js:195:7)"
    ]
}

**Comment by swapnilsaykar** [comment]
Same issue as this - https://github.com/alexa/skill-sample-nodejs-fact/issues/26

**Comment by soundarsurya** [comment]
i am getting this error "The remote endpoint could not be called, or the response it returned was invalid."
how it will be fixed../???

**Comment by memodoring** [comment]
You will typically get that error when the JSON object your lambda function is sending back is malformed. 

To debug the exact error, copy the JSON generates by the simulator and paste it as a test event in the lambda console.

**Comment by soundarsurya** [comment]
when i did that i am getting...
**{
  "errorMessage": "RequestId: 05bd74d6-051e-11e8-aff0-c57fcaf78aa9 Process exited before completing request"
}**

what this means...???
