### ISSUE TITLE
This tutorial needs upgrading

### ISSUE THREAD

**Issue by aledalgrande** [alexa/skill-sample-nodejs-fact#28]
The interface has some changes/additions, mostly due to the new Echo Show I think.

**Comment by cyanliu-zzz** [comment]
Along that same vein of thought, I was wondering why all of the steps feature redundant screenshots; they don't really render too clearly on retina and/or larger displays. I get that it's not really feasible to write and style actual elements in Markdown, but in events like these when the interface changes, the screenshots lose their value

**Comment by daverathbone** [comment]
Yep ... Here you will find outdated work, not supported by Amazon? look for more current demos before time investment

**Comment by franklin-lobb** [comment]
@aledalgrande We have updated the sample since the release of the new SDK.  Other updates are in the works.  If you have specific suggestions for this sample, please open new issue(s) with them.  You can also submit requests through [developer voice](https://alexa.uservoice.com).
