### ISSUE TITLE
Sample app does not handle exit/quit/close

### ISSUE THREAD

**Issue by TDA** [alexa/skill-sample-nodejs-fact#3]
Hello,
The sample app does not seem to handle the phrases "Exit/close/quit" even though these are required for certification. Whats more, even if you _do_ add these to the `sample utterances` and test out on developer.amazon.com, it does not seem to work at all:

```
AMAZON.StopIntent exit
AMAZON.StopIntent close
AMAZON.StopIntent quit
```

Also, just testing this on Lambda, with a `Alexa End session` with edited App ID fails with the message:

```
{
  "errorMessage": "No 'Unhandled' function defined for event: Unhandled",
  "errorType": "Error",
  "stackTrace": [
    "AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:140:15)",
    "AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:110:23)",
    "AlexaRequestEmitter.Object.defineProperty.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:72:31)",
    "exports.handler (/var/task/index.js:34:11)"
  ]
}
```

EDIT: Similar to : https://forums.developer.amazon.com/questions/5938/error-with-utterances-quit-exit-remote-endpoint.html
EDIT2: The sample app does handle `stop` but apparently this is not sufficient for certification
What could the issue be?
@PaulCutsinger 
@deegles

**Comment by RedRoxProjects** [comment]
Hey @TDA @PaulCutsinger @deegles - I encountered this issue when trying something with the alexa skill sample at a hackathon, couldn't find a way out once I'd got into the error - are there any updates on this?

**Comment by TDA** [comment]
@DickensA tbh, I never got a response to this, I just re-submitted a bunch of times and gave up. There is an article on the forums for this, apparently this need not be supported: https://forums.developer.amazon.com/forums/thread.jspa?threadID=8941&tstart=0
But the reviewers dont seem to know that. :\

**Comment by delianides** [comment]
Your app might need to respond to an `Unhandled` option as a possibility for Intents.

```
Unhandled() {
    this.emit(':ask',
      `I\'m sorry, but I\'m not sure what you asked me.`
  },
```

I found this out when I misspelled an intent and the app didn't know how to process the request. Kind of acts like a `default` option inside a switch statement.

**Comment by varungoyal44** [comment]
I have this function in the code, it still seems to be stuck!

**Comment by varungoyal44** [comment]
I found the error in my code, I was missing:-
the "Unhandled" function at first then i was missing 
module.exports = handlers;

in the intentHandlers.js

**Comment by AndyMayJE** [comment]
Exit is a command baked into Alexa.

If you receive this error when saying 'exit' 

> No 'Unhandled' function defined for event: Unhandled

You can add this intent to your handler to capture exit and clean up any sessions:

```
'SessionEndedRequest': function () {
  console.log('session ended!');
 }
```

**Comment by TDA** [comment]
@JennJin I see that you have closed a bunch of issues today, is there an official way to handle this? I would like to see a response from the core team on what the right way to solve this is, before closing it out.

**Comment by JennJin** [comment]
@TDA, sorry for the confusion. I've been asked to go through and close out 'old' open Issues. 

I closed this one because it's not an issue with the sample code.

"Exit" and "Quit" are reserved words for a 'hard exit' on a Session. They route to a System Intent that immediately ends the current session. The skill will receive a "SessionEndRequest" with the 'Reason' = "USER_INITIATED".
["SessionEndRequest" Request Type](https://developer.amazon.com/docs/custom-skills/request-types-reference.html#sessionendedrequest)

So you don't need to handle for "Exit" and "Quit". 
Sending a response to a Request Type of 'SessionEndRequest' will result in Alexa replying back with an error that appears in your CloudWatch Logs.

It would be great to continue the discussion on the [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) .

**Comment by TDA** [comment]
@JennJin Thanks for the detailed explanation :) That is pretty much what I expected, it appears that the certification team isn't caught up with that yet. I will continue the discussion on the forums. Thank you!

**Comment by Shivam-Singh-02** [comment]
Hey Guys that's a very genuine question. I figured out if you add "SessionEndedRequest" intent before your "LaunchRequest" intent(You can put it anywhere though) and inside it just have "this.emit(':responseReady')" and nothing else. Works fine.
