### ISSUE TITLE
Cannot find module 'alexa-sdk'" error at LAMDA FUNCTION

### ISSUE THREAD

**Issue by JOSEPHREDDY07** [alexa/skill-sample-nodejs-fact#33]
I'm new to Alexa skills, I fallowed all the steps. Here's the error I get on this line "var Alexa = require("alexa-sdk");". Am I doing something wrong? Or is there some configuration setting I need to do?

{
"errorMessage": "Cannot find module 'alexa-sdk'",

**Comment by robwhite4** [comment]
You should fire up a terminal (as administrator) and ->

``` bash
cd <my/project/dir>
npm install
```

This will install the project deps (from the package.json file) into a `node_modules` directory from which your project can access them.

See: https://docs.npmjs.com/cli/install for more.

Hope this helps.

Good luck!  👍

**Comment by robwhite4** [comment]
Also, I guess you are coding your function on Lambda directly.  I can't guide you in requiring external libraries on lambda from their code editor.  I use [serverless](https://serverless.com/) to package and deploy my lambda functions.  

There are others, but I haven't played with them much; which are:

* [Claudia Js](https://claudiajs.com/)
* [APEX](http://apex.run/)

(..there are more but I can't think of them atm..)

It takes a little more work, but these tools allow you to use your local setup to code up these items.

Maybe this will also be of assistance to you.

Thanks.
