### ISSUE TITLE
Amazon Alexa Development Site Changed!

### ISSUE THREAD

**Issue by daverathbone** [alexa/skill-sample-nodejs-fact#38]
This Alexa skill sample documentation needs  updating to reflect to changes made in the developer console.
If you would like help more developers you should UPDATE your documentation as this makes this current sample guide for development using its tools near impossible!!!!
If you did put this repository to help others great! if not remove it we don't need to feed your star ego!

**Comment by JennJin** [comment]
I completely understand your frustration. The Team has every intention of ensuring the content is kept up to date, but at times fall behind. We welcome any assistance from the Alexa Dev Community to help us keep the content current.
