### ISSUE TITLE
t.t0.message.includes in a not a function

### ISSUE THREAD

**Issue by radski** [alexa/skill-sample-nodejs-fact#4]
I'm following the tutorial (https://developer.amazon.com/public/community/post/Tx3DVGG0K0TPUGQ/New-Alexa-Skills-Kit-Template:-Step-by-Step-Guide-to-Build-a-Fact-Skill) and getting "t.t0.message.includes in a not a function" when trying to create the lambda action (after uploading the zip). Just posting this in case anyone knows the resolution and for future reference.

**Comment by deegles** [comment]
Hi Radski,

Could you provide more details on how you built the zip and your code changes?

**Comment by radski** [comment]
Hi deegles, thanks for coming back. I was just following the tutorial so no custom changes. Pull from here, zipped up content of the src directory and tried doing step 12 of the tutorial "Create Function". (click create fuction to get ARN). This is where the error message appears. Screengrab attached.
![lambda management console - mozilla firefox_2016-09-25_13-09-41](https://cloud.githubusercontent.com/assets/16647248/18815211/619fb116-8321-11e6-8ae7-90a3728663a1.png)

**Comment by lirenlin** [comment]
I had exactly the same issues when using python execution environment.
Not matter what I put in the code.

**Comment by hemkantc** [comment]
Hi ,
I am also getting the same error while creating Hello World lambda using Node JS.
I checked on my friend's account , he is able to create it successfully. But when tried the exact config its giving me the annoying error.
Also there is nothing on AWS or google for it.
Please let us know if anybody is able to resolve it.

**Comment by radski** [comment]
That's interesting hemkantc - did you try on the same computer/same browser?

**Comment by lirenlin** [comment]
I tried it on Chrome browser, it works. However, firefox doesn't.

**Comment by radski** [comment]
Thanks lirenlin,
the reason for not using chrome was that the upload doesn't work there, but it does in FF.
![image](https://cloud.githubusercontent.com/assets/16647248/19744281/beae06f8-9bc4-11e6-844f-fb3ba19370e6.png)

same on Opera by the way ...
