### ISSUE TITLE
Cannot find module './question'

### ISSUE THREAD

**Issue by polyren** [alexa/skill-sample-nodejs-fact#41]
I copied and pasted the code then tested, but it doesn't work.
{
  "errorMessage": "Cannot find module './question'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:417:25)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/index.js:16:19)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)"
  ]
}
when I call this function in ASK, it doesn't retrun anything.
Anyone here can help me?

**Comment by JennJin** [comment]
I don't see the './question' module in the index.js:
https://github.com/alexa/skill-sample-nodejs-fact/blob/en-US/lambda/custom/index.js

Where do you see that code? I don't think this is the right Repo.

**Comment by SleepyDeveloper** [comment]
The fact sample skill doesn’t load any modules called question, but the trivia sample skill does.  The trivia skill has a different set of instructions to deploy to Lambda. You’ll either have to upload a zip file or use the ask cli to push up your code. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by polyren** [comment]
I fixed this issue by creating a new project folder, thank you guys. I will close this question
