### ISSUE TITLE
Skill works fine in Simulator, but anything beyond the opening invocation fails to work

### ISSUE THREAD

**Issue by TylerNoblett** [alexa/skill-sample-nodejs-fact#48]
Hi! I followed this tutorial and submitted a skill to Amazon. I forgot about and came back two months later to see it had a fair amount of use, but the 1 review posted said that it opened but that subsequent commands didn't work. I checked the metrics, and that appears to be the case for everyone who downloaded it. 

I didn't have any issues in the simulator, but when I tested it on echoism.io I had the same issue. Here's the code I'm using compared to the source code, and some screenshots. What am I doing incorrectly? My app is called "Good Questions" fyi.

[Here's the index code comparison.](https://www.diffchecker.com/VpBVNRph) 
[Here's the json file.](https://www.diffchecker.com/pGnjhunu) It looks a little different, but when I submitted it to Amazon it was the same and it appears that the code was deprecated and the skill builder updated it automatically.

Here's a screenshot of my skill builder - 
<img width="839" alt="getnewfactintent" src="https://user-images.githubusercontent.com/22867407/33793968-57813764-dce8-11e7-81aa-56a08173aced.png">

and my metrics
<img width="1242" alt="metrics" src="https://user-images.githubusercontent.com/22867407/33793969-5ff59b2e-dce8-11e7-95c7-1751752c8949.png">

Let me know if you need anything else - thanks in advance!

**Comment by TylerNoblett** [comment]
I figured it out - I replaced. 
```
//this.response.speak(speechOutput); 
//this.emit(':responseReady'); 
```
with
` this.emit(':ask', speechOutput, HELP_MESSAGE);`
and now it works just fine

**Comment by jnicho02** [comment]
yeah, responses in [alexa-sdk](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs) can be defined in either way. If you use the :responseReady style and want to accept user input then it needs to .listen(..) otherwise it is the same as a :tell.

```javascript
this.response.speak(speechOutput)
             .listen(repromptSpeech);
this.emit(':responseReady');
```
