### ISSUE TITLE
Bad link to code in creating lambda function tutorial

### ISSUE THREAD

**Issue by paveljamal** [alexa/skill-sample-nodejs-fact#50]
https://github.com/alexa/skill-sample-nodejs-fact/blob/en-US/instructions/2-lambda-function.md

Critical step linking to the code is returning 404 where it says "Copy and paste the *provided code* into the Lambda function code box.".

**Comment by akersh-s** [comment]
@paveljamal @JennJin @SleepyDeveloper Just checked the link. Looks like this works, closing the issue.
