### ISSUE TITLE
Gloucester facts doesn't exist

### ISSUE THREAD

**Issue by dfrho** [alexa/skill-sample-nodejs-fact#57]
Mentions listening to this skill in action by adding skill "Gloucester Facts", which isn't on the marketplace when searched, also a dead link from the ReadMe.

**Comment by nduckwiler** [comment]
+1 to this issue: The "Gloucester" link is dead in `README.md` and `0-intro.md`

**Comment by franklin-lobb** [comment]
The link has been removed.  As you've noted, that skill is not currently available.
