### ISSUE TITLE
Docs: Broken link to "Interaction Model"

### ISSUE THREAD

**Issue by jazzfog** [alexa/skill-sample-nodejs-fact#61]
This page: https://github.com/alexa/skill-sample-nodejs-fact/blob/en-US/instructions/1-voice-user-interface.md

Has pretty important link that is broken - "Interaction Model" points to not-existing json file
https://github.com/alexa/skill-sample-nodejs-fact/blob/en-US/interactionModel.json

There is a file https://github.com/alexa/skill-sample-nodejs-fact/blob/en-US/models/en-US.json in repo
but it didnt work for me as model.

Also there is a typo here: https://github.com/alexa/skill-sample-nodejs-fact/blob/en-US/instructions/2-lambda-function.md
"You mays till have"

**Comment by seanbode** [comment]
This is probably already solved, but I wanted to share this as a solution until this is fixed. The Sample Interaction Model Schema at the bottom of the page, https://developer.amazon.com/docs/smapi/interaction-model-schema.html, saved successfully when I was having a similar issue.

**Comment by franklin-lobb** [comment]
There have been a few updates recently and it looks like has been resolved.
