### ISSUE TITLE
リンク切れ

### ISSUE THREAD

**Issue by yukiando** [alexa/skill-sample-nodejs-fact#64]
https://github.com/alexa/skill-sample-nodejs-fact/blob/ja-JP/instructions/2-lambda-function.md

「Lambda関数のコード入力ボックスに必要なコードを貼り付けます。このスキル用のコードは GitHubにあります。コード入力ボックス内のコードを削除し、この新しいコードを貼り付けてください。」

のGitHubがリンク切れしています。更新していただけますか。

**Comment by SleepyDeveloper** [comment]
@yukiando　切られているリンクがもう修正されたようです。

このIssueをCloseします。もし、まだリンクに関する問題であれば、このissueを再開して下さい。
