### ISSUE TITLE
alexa-cookbook.js

### ISSUE THREAD

**Issue by sohanmaheshwar** [alexa/skill-sample-nodejs-fact#74]
Hey franklin

Is this line required? it also will throw an error when copied to a lambda SAR

`const cookbook = require('alexa-cookbook.js');`

**Comment by franklin-lobb** [comment]
the helper functions were moved into that file.  the required file has not made it into the SAR yet.  I will check on that for you.

**Comment by franklin-lobb** [comment]
updating the template is still in progress, however in the meantime, you can create a file in the Lambda function console (File menu >> New File) and then paste the contents into it.  When saving it, name it alexa-cookbook.js and save it to the "/" folder.

**Comment by jollyjess310** [comment]
Hi! New to coding/Alexa here. 

What code am I supposed to paste into the new alexa-cookbook.js file? I've looked for the helper functions code and cannot find it. Thanks!

**Comment by franklin-lobb** [comment]
The code from here: https://github.com/alexa/skill-sample-nodejs-fact/blob/en-US/lambda/custom/alexa-cookbook.js
