### ISSUE TITLE
Lambda Code Inline does not display code.

### ISSUE THREAD

**Issue by edacostacegb** [alexa/skill-sample-nodejs-fact#75]
Hello.

I am in tokyo so my region in Alexa dev is Tokyo

I have followed the instruction to create a space fact skill.
I arrive at the lambda configuration step, I create the function, set the trigger.
(My region in Lambda is ap-northeast-1)
When I try to open the function code in the inline editor, the editor does not display anything. The icon is moving and moving.

I can not check nor the default code neither the code I want to publish.

Regards

Emmanuel

**Comment by franklin-lobb** [comment]
I have seen this once before.  Try a hard refresh on your browser or clearing your browser cache.  In the other case, the person switched to a different browser and it worked.

**Comment by edacostacegb** [comment]
Hello

Sorry for the late reply.
I have opened lambda in another browser and it worked.

thanks 

Regards

Emmanuel
