### ISSUE TITLE
Simulator spins with no response after invoking skill

### ISSUE THREAD

**Issue by awaemmanuel** [alexa/skill-sample-nodejs-fact#78]
I have configured everything up to the Test stage. I invoke it with `open space geek` and it just spins there and does nothing. Is this a known issue?

**Comment by franklin-lobb** [comment]
unless you changed the invocation name, try ```open space facts```

**Comment by awaemmanuel** [comment]
@franklin-lobb I changed the invocation name to `space geek` and changed it back to `space facts`. Also reverted everything, followed the tutorial again and still not luck. Below is a screenshot of where it gets stuck. 
<img width="1215" alt="screen shot 2018-06-07 at 11 02 39 pm" src="https://user-images.githubusercontent.com/3170798/41137362-c984d228-6aa8-11e8-9418-33ccf136c3f2.png">

**Comment by franklin-lobb** [comment]
I have only seen that when the message is first sent to the endpoint, and then it turns into your utterance.  Perhaps there is something in the browser or the cache causing a problem.  If you try in a different browser, we can rule that out.  Also, if you check the Device Log box, and scroll down, you'll see more detail on what is sent and received.

**Comment by awaemmanuel** [comment]
@franklin-lobb After a painful debug session, I figured out it was a CORS issue. I tried to enable it with plugins and chromium flags with no luck. Finally I realized it was my antivirus software that was the issue. I disabled web shield and it worked.
