### ISSUE TITLE
[Error]: Failed to deploy. Please ensure current working directory is the root of your skill project.

### ISSUE THREAD

**Issue by lubianat** [alexa/skill-sample-nodejs-fact#81]
Hey, after changing the directory where all my files are I get the following error: 
[Error]: Failed to deploy. Please ensure current working directory is the root of your skill project.

AWS CLI is properly configured. Do you have a guess of what could be happening?

Thanks for your time

**Comment by franklin-lobb** [comment]
The ASK-CLI needs to be run from the directory where the skill.json file resides.  In that same directory, there needs to be a .ask sub-directory, and a proper config file in that folder.  If you run ask new (which can be run from any directory), you can examine the resulting folder structure and compare it to the one you're having problems with.

**Comment by franklin-lobb** [comment]
if you're still experiencing this issue, please re-open the issue or open a new one.
