### ISSUE TITLE
Intents dont launch, only invocations.

### ISSUE THREAD

**Issue by nikkopante** [alexa/skill-sample-nodejs-fact#84]
When you test and utter the sample utterance, the skill wont launch. It only launches when invocation name is called. The Python space facts also do the same.

**Comment by srlodd** [comment]
I have the exact same problem. In fact if worked for some time and I dont know what happened later.

**Comment by chfw** [comment]
I am beginner here. what's the difference between invocation and launch?

**Comment by franklin-lobb** [comment]
@chfw invoking a skill is the same thing as launching the skill.

**Comment by franklin-lobb** [comment]
@cnpants @srlodd the skill doesn't keep a session open after it tells you a fact, so you have to use the invocation name each time you want to use the skill.  If you wanted to trigger an IntentRequest as opposed to a LaunchRequest, you'll need to include an utterance (e.g. give me a fact) with the inocation name (e.g. ask space facts to get me a fact).  Alternatively, you could use .reprompt() to keep the session open, and then you could ask for a fact and trigger the GetNewFactIntent

**Comment by franklin-lobb** [comment]
if you're still experiencing this issue, please re-open the issue or open a new one.
