### ISSUE TITLE
Sample is not ready for FR-fr

### ISSUE THREAD

**Issue by RolandLeFranc** [alexa/skill-sample-nodejs-fact#85]
Looking at the folder skill-sample-nodejs-fact/models/, there is no sample interaction model for the French locale.
In particular, what sample utterances would you recommend using in French for "tell me a fact"?

**Comment by baezor** [comment]
Same with es-mx spanish language. I'd like to contribute with this.

**Comment by franklin-lobb** [comment]
both es-MX and fr-FR models have now been added to the master branch.  
https://github.com/alexa/skill-sample-nodejs-fact/blob/master/models/es-MX.json
https://github.com/alexa/skill-sample-nodejs-fact/blob/master/models/fr-FR.json
If that doesn't get you what you were looking for, please reopen the issue.
