### ISSUE TITLE
Broken link in ja-JP/instructions/3-connect-vui-to-code.md

### ISSUE THREAD

**Issue by thvinmei** [alexa/skill-sample-nodejs-fact#86]
The link destination of "_Alexa ユーザーとシステムユーザーを関連付ける_" has a 404 error.
The current link is on top, but correctly is probably not the one below.

[current]
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/linking-an-alexa-user-with-a-user-in-your-system
[correct?]
https://developer.amazon.com/ja/docs/custom-skills/link-an-alexa-user-with-a-user-in-your-system.html

**Comment by toshimin** [comment]
Thank you, we will make it updated.

**Comment by franklin-lobb** [comment]
the referenced link has been removed from the page, so problem solved.  Thanks for the feedback!
