### ISSUE TITLE
Tutorial for ask-cli does not work

### ISSUE THREAD

**Issue by fahimmm** [alexa/skill-sample-nodejs-fact#88]
Hi,

the tutorial does not work completlty. If I try to enable the skill I get the error:

Call enable-skill error.
Error code: 403
{
  "message": "Skill is not ready for enablement.",
  "violations": [
    {
      "message": "custom - object has missing required properties ([\"endpoint\"])"
    }
  ]
}

So I guess that some configuration is missing?

![alexa_skill_kit_entwicklerkonsole](https://user-images.githubusercontent.com/8937973/43255045-0dcd9c94-90c9-11e8-82d1-a80c45a22b4e.png)

**Comment by franklin-lobb** [comment]
Check the output from your `ask deploy` command.  That command creates the skill, builds the interaction model, uploads the code to AWS Lambda, and then connects the Lambda function with the skill.  If the endpoint is not configured, it typically means that the Lambda function did not get created correctly.

**Comment by franklin-lobb** [comment]
if you still see this issue, please reopen this issue or open a new one.
