### ISSUE TITLE
Select the ‘Code Entry Type’ as ‘Upload Zip File’ and upload the zip file containing the example you created in Step 1. 

### ISSUE THREAD

**Issue by stratospheres** [alexa/skill-sample-nodejs-fact#9]
There's no description of creating such a zip file.  It appears that this is telling me to pull the repo and create a ZIP file with a portion of the source files, but this is really confusing, especially for an intro level tutorial.  The tutorial should have clear instructions on how to get this file.

**Comment by stratospheres** [comment]
Now that I work through it, it appears that not only do you need to pull the repo, but you need to restore the node_modules directory (not included in the repo) by doing an "npm restore" as well.  Definitely not an entry level tutorial thing, especially for Node newbies.  Definitely deserves a pretty clear walkthrough on getting the source ready for the Lambda by pulling the repo, restoring the node_modules, and then zipping up a new ZIP file in the format desired by the Lambda pages on AWS.

**Comment by khearnshaw** [comment]
I see I'm not the only one having this issue. Completely stuck here and no idea how to create this zip file. 

@stratospheres I don't suppose you could share the correctly formatted zip file or instructions for how to create it could you? I'm one of the Node newbies you speak of :)

**Comment by jMCHammer** [comment]
@khearnshaw this requires npm to be installed. If not already, the steps can be found here https://docs.npmjs.com/cli/install .

`cd src`
`npm install`
to resolve dependencies. Then zip the src folder contents. That should work.
